name: haskell-ci
version: 0.1.0.0
github: 'githubuser/haskell-ci'
license: BSD3
author: 'Author name here'
maintainer: 'example@example.com'
copyright: '2022 Author name here'

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/haskell-ci#readme>

default-extensions:
  - BlockArguments
  - DeriveAnyClass
  - DeriveGeneric
  - LambdaCase
  - NoImplicitPrelude
  - OverloadedStrings
  - StrictData

dependencies:
  - aeson
  - async
  - base
  - butcher
  - bytestring
  - hslogger
  - http-client
  - http-conduit
  - http-types
  - network
  - record-hasfield
  - rio
  - scotty
  - serialise
  - stm
  - time
  - typed-process
  - wai-cors
  - yaml

ghc-options:
  - -F -pgmF=record-dot-preprocessor

library:
  source-dirs: src

executables:
  haskell-ci-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-ci

tests:
  haskell-ci-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-ci
      - hspec
